'((rel "index" "index")
  (rel "resume" "resume")
  ;(rel "research" "research")            
  (rel "links" "links")
  (rel "blogroll" "blogroll")
  (abs "http://www.flickr.com/photos/23659913@N00/" "photos@")
  ; (abs "http://www.livejournal.com/users/john_and_alyssa/" "blog@")
  (abs "http://www.jmchilton.net/blog" "blog@")
  ;(abs "http://www.bloglines.com/blog/jmchilton/" "clipblog@")
  (abs "http://www.google.com/calendar/embed?src=jmchilton%40gmail.com" "calendar@")
  (abs "http://twitter.com/jmchilton" "twitter@")
  ;(abs "http://profile.myspace.com/index.cfm?fuseaction=user.viewprofile&friendid=39869908" "myspace@")                                                                                            
  (abs "http://www.linkedin.com/in/jmchilton" "linkedin@")
  (abs "http://www.facebook.com/jmchilton" "facebook@")
  (rel "school:index" "school/")
  (rel "geek:index" "geek/")
  (rel "contact" "contact")
  (rel "sitemap" "sitemap"))

